name: CI

on:
  push:
    branches:
      - main

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.VITE_GITHUB_ACCESS_TOKEN }}
        run: |
          curl --request GET \
          --url "https://api.github.com/repos/pruekjika/GardenImgDB/contents/ImageDB/Fixed/" \
          --header "Authorization: Bearer $GH_TOKEN"
